# version: "3"
services:
  client:
    #サービス名
    build:
      # Dockerfileの設定
      context: ./client # Dockerfileを置いているディレクトリ
      dockerfile: Dockerfile # Dockerfileのファイル名
    volumes:
      #バインドマウント
      - ./client:/usr/src/client
    container_name: client
    tty: true # コンテナを正常終了するのを防ぐ
    ports:
      - "3000:3000"
    command: /bin/sh -c "npm install; npm run dev"
    environment:
      - NODE_ENV=development
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      #バインドマウント
      - ./server:/usr/src/server
    container_name: server
    ports:
      - 8000:8000
    tty: true
    command: /bin/sh -c "go run main.go"
